device: 'cuda'
video_path: '/mnt/petrelfs/wangyiqin/vid_cap/examples/videos/'
video_name: 'cook_720p.mp4'
fps: 120

vicuna:
  model_path: '/mnt/petrelfs/wangyiqin/vid_cap/vicuna-13b'
  device: 'cuda'
  num_gpus: 1
  max_gpu_memory: '40Gib'
  load_8bit: False
  conv_template: 
  temperature: 1.0
  max_new_tokens: 512
  debug: False
  output_path: '/mnt/petrelfs/wangyiqin/vid_cap/VideoChatDuplicate/examples/test.json'

vid2seq:
  clip_path: '/mnt/petrelfs/wangyiqin/vid_cap/examples/ViT-L-14.pt'
  basename: 'test'
  output_path: '/mnt/petrelfs/wangyiqin/vid_cap/examples/'
