device: 'cuda'

vicuna:
  model_path: '/YourRootDir/ChatVID/vicuna-7b'
  device: 'cuda'
  num_gpus: 1
  max_gpu_memory: '24Gib'
  load_8bit: True
  conv_template: 
  temperature: 1.0
  max_new_tokens: 512
  debug: False
  output_path: '/YourRootDir/ChatVID/examples/vicuna_out.json'

vid2seq:
  enable: True
  clip_path: '/YourRootDir/ChatVID/clip_ckpt/ViT-L-14.pt'
  output_path: '/YourRootDir/ChatVID/examples/'
  work_dir: 'vid2seq_workdir'
  config_path: 'config/vid2seq_config.py'
  checkpoint_path: '/YourRootDir/ChatVID/vid2seq_ckpt' #only folder name
